### ISSUE TITLE
Use standard modal in file upload error screen

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/verifywise#168]
Here is what we have now: 

<img width="504" alt="image" src="https://github.com/user-attachments/assets/7af414a6-f4c2-4c63-8f82-f8ca8dcf7828">

This needs to be styled to look like the [popup on Figma](https://www.figma.com/design/o4xu4PeC5bo1Ii4dyom6vQ/VerifyWise?node-id=1782-2451&t=OKpO8xfcTbnMvFHk-1).

**Comment by melpsh** [comment]
Hi Gorkem,
@gorkemcetin 
Here's the scenario: when a user selects an unacceptable file, a pop-up prompts them to upload a different, acceptable file. However, the pop-up you linked to this issue is related to account deletion, so it doesn’t align with the file upload process. For consistency, I’ve changed the text color to black across all pop-ups. Is there anything else you want me to change?

**Comment by gorkem-bwl** [comment]
Right. I just wanted to link to a reference modal. It's ok that we change the text, so we are good here 👍
