### ISSUE TITLE
Navigation bar design

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/verifywise#3]
The navigation bar of the VerifyWise application acts as the central routing tab used for navigating between the different pages on the application. 

The navigation bar consists of a sidebar which contains the routes to "Dashboard", "Compliance tracker", "Assessment tracker", "Vendors", "Settings" and "Teams" links

The user icon should have a dropdown with the option to sign out.

![sidebar](https://github.com/user-attachments/assets/e029dd93-9b98-4b4b-b748-eb9ead2c0c3a)

- [x] Implement navigation sidebar
   - [x] General layout
   - [x] "Dashboard" link
   - [x] "Compliance tracker" link
   - [x] "Assessment tracker" link
   - [x] "Vendors" link
   - [x] "Settings" link
   - [x] "Teams" link

- [x] Implement profile dropdown(up) menu (open and close state)
   - [x] "Log out" link

- [x] - Changes in the design
- [x] - Add Logo

**Comment by MuhammadKhalilzadeh** [comment]
I'm checking the **"Log out link"** since it is done in the aspect of creating its function as a **placeholder** to just simply `console.log` that the user has logged out but in order to really log out of the **Dashboard**, _the login and authentication mechanism needs to be implemented_.
So we'll need an issue for that for the **Application Layer**
